SCF-46: [Dashboard] Replace flyer bears image with higher-resolution SVG
sproul-club/sc-frontend pull request #280
Opened 2021-11-02 22:00 UTC by Gabe-Mitnick

[SCF-46](https://scfrontend.atlassian.net/browse/SCF-46?atlOrigin=eyJpIjoiNzExNjllZTI4MjY0NDBlMmI4NmNlNjQ2OGNlYWJlNzAiLCJwIjoiaiJ9). I replaced the dashboard flyer bears .svg with a sharper one. The old one just contained a .png so it wasn't actually a vector graphic. Now the bears on the dashboard should look nice and sharp.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/16441620/139957790-13700ccc-14db-4846-873e-a36c0eb12532.png">

2021-11-02 22:09 UTC, tankaren approved these changes

2021-11-03 22:06 UTC, Gabe-Mitnick commented
Wait sorry I noticed the club login page has the same graphic but is a png and should be the same svg so I changed that too. And I moved the image on the dashboard to the right to match the design. @tankaren could you review those before we merge?

2021-11-04 10:38 UTC, tankaren requested changes
The new changes looks good! Can I actually toss on one more request? We noticed the picture looks really fcking big when you zoom out lol (see attached screenshot). In Dashboard.scss file, can we instead have

```
.dashboard-flyer-bears-img {
    display:flex;
    width: 472px;
    height: 386px;
}
```

![image](https://user-images.githubusercontent.com/40283466/140299411-26fa7d52-4365-45e5-b8aa-95f7e5c66d49.png)

2021-11-04 17:17 UTC, Gabe-Mitnick commented
Fixed. I also added a margin-top with a pixel value so the position of the bears image still matches the design.

2021-11-04 17:30 UTC, allenli75 approved these changes

2021-11-05 00:35 UTC, tankaren approved these changes

2021-11-05 01:41 UTC, merged