SCF 29 Turn Searchbar Into a Component
sproul-club/sc-frontend pull request #292
Opened 2021-11-09 10:24 UTC by jeyu21

SCF-29. I made searchbar a component and added it to the components/layout folder. 
I changed the searchbar in Catalog, Bookmarks, and AppTracker
I made it so that the searchbar becomes width: 100% after the page becomes smaller.

https://user-images.githubusercontent.com/21046037/140906894-8aec90fd-3f38-4f73-b55d-5e7baee46773.mov

https://user-images.githubusercontent.com/21046037/140907012-ea99c0a6-c4d0-4afd-b406-e3fa40e32c4b.mov

https://user-images.githubusercontent.com/21046037/140907097-611d6d20-acbc-4ee7-ab0e-9d6793df49bf.mov

2021-11-09 18:21 UTC, allenli75 commented on src/components/layout/searchbar/Searchbar.js
> +        </span>
```suggestion
        { showReset && <span className="reset-filters" onClick={() => click()}>
            reset filters
        </span> }
```

2021-11-09 18:31 UTC, allenli75 requested changes
hi @jeyu21 suggested some changes! i saw your comment about the search on the modal looking sus and i assumed you were referring to the reset button but lmk if that's wrong.

the reset button shouldn't appear on the application tracker modal anyway so i think it's fine that it looks weird for now. it looks that way because the "reset filters" button is a span with no margins...

tim has a ticket this week to work on building the entire modal and karen is working on refactoring the entire filter bar component so it should be sorted out eventually, but what we can do rn is make the reset button conditionally rendered (the suggestions should take care of that but if you want to learn more about conditional rendering: https://reactjs.org/docs/conditional-rendering.html)

2021-11-09 18:31 UTC, allenli75 commented on src/components/layout/searchbar/Searchbar.js
> +const Searchbar = ({click, value, searchClubs}) => {
```suggestion
const Searchbar = ({click, value, searchClubs, showReset}) => {
```

2021-11-09 18:31 UTC, allenli75 commented on src/pages/catalog/Catalog.js
> +            <Searchbar value={name} searchClubs = {changeSearch} click = {resetFilters}/>
```suggestion
            <Searchbar value={name} searchClubs = {changeSearch} click = {resetFilters} showReset = {true}/>
```

2021-11-09 18:31 UTC, allenli75 commented on src/pages/student/AppTracker.js
> +        <Searchbar value={name} searchClubs = {changeSearch} click = {resetFilters}/>
```suggestion
        <Searchbar value={name} searchClubs = {changeSearch} click = {resetFilters} showReset = {false}/>
```

2021-11-09 18:31 UTC, allenli75 commented on src/pages/student/Bookmarks.js
> +          <Searchbar value={name} searchClubs = {changeSearch} click = {resetFilters}/>
```suggestion
          <Searchbar value={name} searchClubs = {changeSearch} click = {resetFilters} showReset = {true}/>
```

2021-11-12 09:54 UTC, jeyu21 commented
Thanks for the comments and commits. Am I able to squash and merge now or should I wait the other developers' code?

2021-11-12 17:24 UTC, allenli75 approved these changes
looks great thank you for addressing the conditional rendering suggestions jenny! can go ahead and squash + merge this PR :)

2021-11-12 19:45 UTC, merged